include ../../mincl.purec

CFLAGS = -I../comm -I../common -I../.. -I../lib \
	 $(INCLUDES) $(DEFINES)

SERVER_OBJS = \
	boot.o debug.o main.o rlist.o srv.o srv_appl_info.o srv_event.o \
        srv_get.o srv_global.o srv_misc.o srv_queue.o srv_wind.o

TRAP_OBJS = purec.o

all: oaesis

oaesis: $(SERVER_OBJS) $(TRAP_OBJS)
	$(LD) -O=$@ $(PCLIBDIR)/crt0.o $(SERVER_OBJS) $(TRAP_OBJS)\
	  ../lib/oaesis_client.lib $(PCLIBDIR)/ovdisis.lib \
	  $(PCLIBDIR)/mintlib.lib
