include ../../mincl.purec

CFLAGS = -I../comm -I../common -I../.. -I../lib \
	 $(INCLUDES) $(DEFINES)

LAUNCHER_OBJS = launch.o launcher.o

all: launcher.lib

launcher.lib: $(LAUNCHER_OBJS) ../lib/oaesis.lib
	$(LD) -O=$@ -J $(LAUNCHER_OBJS)

launch.c launch.h: launch.rsc launch.hrd
	../../tools/r2c_raw launch.rsc
